### PR TITLE
Adding an Example for a Standalone Primary Site

### PR DESCRIPTION
**Pull request by NEllis280**
#### Pull Request (PR) description
This PR is to add a full example demonstrating basic standup of a standalone Primary Site Server.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69)

### CODE REVIEW

**Review by rchristman89 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69)* status: all files reviewed, 4 unresolved discussions (waiting on @NEllis280)

___
*[source/Examples/PrimaryInstall.ps1, line 80 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFp-Hw24iisDbhgHvn:-MLFp-HxC2w6mGycpgum:bmcabu2) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L80)):*
> ```PowerShell
>         }
> 
>         $serverShortName = $ServerName.split('.')[0]
> ```

casing
```
$ServerName.Split('.')[0
```

___
*[source/Examples/PrimaryInstall.ps1, line 151 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFprSg08BICY59yAeA:-MLFprSg08BICY59yAeB:bepqzak) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L151)):*
> ```PowerShell
> 
>         #Install WSUS features
>         WindowsFeatureSet WSUSFeatures
> ```

This fail to compile do to this. When you specify:
`SccmRole               = 'CASorSiteServer','ManagementPoint','DistributionPoint','SoftwareUpdatePoint'`
it includes:
```
 'SoftwareUpdatePoint' {$features += 'Net-Framework-45-Core','Net-Framework-Core',
      'NET-Framework-45-ASPNET','UpdateServices-RSAT','UpdateServices-API','UpdateServices-UI',
      'Web-Asp-Net45','Web-ISAPI-Ext','Web-ISAPI-Filter','Web-Net-Ext45','Web-Default-Doc',
      'Web-Static-Content','Web-Dyn-Compression','Web-Filtering','Web-Windows-Auth','Web-Mgmt-Console',
      'Web-Metabase','UpdateServices-Services','UpdateServices-DB','WAS-Config-APIs'
  }
```
___
*[source/Examples/PrimaryInstall.ps1, line 241 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFqnNdBCQgcDqujJln:-MLFqnNdBCQgcDqujJlo:bgrr5y1) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L241)):*
> ```PowerShell
>             }
>             SetScript  = {
>                 $process = Get-Process | Where-Object -FilterScript {$_.Description -eq 'Configuration Manager Setup BootStrapper'}
> ```

Couldn't you just do
````
Get-Process -Name (The Name of the service here) -ErrorAction SilentlyContinue
```

___
*[source/Examples/PrimaryInstall.ps1, line 548 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFsfXS6cXS6lOe8X84:-MLFsfXS6cXS6lOe8X85:by3rmjl) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L548)):*
> ```PowerShell
>             }
>             GetScript = { return @{result = 'result'}}
>             DependsOn = $cmAccountsDependsOn,'[CMForestDiscovery]CreateForestDiscovery','[CMSystemDiscovery]CreateSystemDiscovery','[CMNetworkDiscovery]DisableNetworkDiscovery',
> ```

Have you guys played with changing this? If for some reason no CMAccounts were created this will error. Since the dependson is only being used here you could just build one chain and add to it after all the resources you have here. 


<!-- Sent from Reviewable.io -->

**Review by NEllis280 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @rchristman89)

___
*[source/Examples/PrimaryInstall.ps1, line 80 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFp-Hw24iisDbhgHvn:-MLI8kcC6d0Td6LUDLw_:b-896fix) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L80)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

casing
```
$ServerName.Split('.')[0
</blockquote></details>

Done.
___
*[source/Examples/PrimaryInstall.ps1, line 151 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFprSg08BICY59yAeA:-MLIA06E-JrHiwiJPNgo:bfrlpd7) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L151)):*
> This fail to compile do to this. When you specify:
> SccmRole               = 'CASorSiteServer','ManagementPoint','DistributionPoint','SoftwareUpdatePoint'
Removed Feature Set
___
*[source/Examples/PrimaryInstall.ps1, line 241 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFqnNdBCQgcDqujJln:-MLIA1muAxDS9aKziZ2E:b6ezbek) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L241)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

Couldn't you just do
````
Get-Process -Name (The Name of the service here) -ErrorAction SilentlyContinue
</blockquote></details>

skipping this one
___
*[source/Examples/PrimaryInstall.ps1, line 548 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFsfXS6cXS6lOe8X84:-MLIA6JmEDe0aaVhRdro:b-e8dz5p) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L548)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

Have you guys played with changing this? If for some reason no CMAccounts were created this will error. Since the dependson is only being used here you could just build one chain and add to it after all the resources you have here. 
</blockquote></details>

Will enhance in future

**Review by NEllis280 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @rchristman89)

___
*[source/Examples/PrimaryInstall.ps1, line 151 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFprSg08BICY59yAeA:-MLIUS0-94Ov39tElCwv:b-896fix) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L151)):*
<details><summary><i>Previously, NEllis280 (Nick) wrote…</i></summary><blockquote>

> This fail to compile do to this. When you specify:
> SccmRole               = 'CASorSiteServer','ManagementPoint','DistributionPoint','SoftwareUpdatePoint'
Removed Feature Set
</blockquote></details>

Done.
___
*[source/Examples/PrimaryInstall.ps1, line 241 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFqnNdBCQgcDqujJln:-MLIUTZM6WlAVvlBguIZ:b-896fix) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L241)):*
<details><summary><i>Previously, NEllis280 (Nick) wrote…</i></summary><blockquote>

skipping this one
</blockquote></details>

Done.
___
*[source/Examples/PrimaryInstall.ps1, line 548 at r2](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69#-MLFsfXS6cXS6lOe8X84:-MLIUUAA21sXzVy6nkB1:b-896fix) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/4842fd0e229753bdc414b977f4519318734ea85e/source/Examples/PrimaryInstall.ps1#L548)):*
<details><summary><i>Previously, NEllis280 (Nick) wrote…</i></summary><blockquote>

Will enhance in future
</blockquote></details>

Done.

**Review by rchristman89 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rchristman89 — APPROVED** [review]

**Review by rchristman89 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/69)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
