### PR TITLE
Add issue and PR template

### LINKED ISSUE #17: Add issue and pull request templates
Suggest adding issue and pull request templates

Example: https://github.com/dsccommunity/ActiveDirectoryDsc/tree/master/.github

### PR DESCRIPTION
**Pull request by rchristman89**
Closes #17

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/26)

### CODE REVIEW

**Comment by rchristman89** [comment]
Are there additional steps after this merges?

**Comment by johlju** [comment]
If you mean a preview release. A preview release will be automatically released when a PR's is merged into master. It can be avoided by adding `[skip ci]` to the merge commit title or description.

**Comment by johlju** [comment]
You need to update the changelog too 😄

**Comment by rchristman89** [comment]
> You need to update the changelog too 😄

Done.

**Pull request merged**
