### PR TITLE
Change pipeline build stage to use windows-latest

### PR DESCRIPTION
**Pull request by NEllis280**
Restricting version of Sampler to pass build

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/112)

### CODE REVIEW

**Comment by johlju** [comment]
Are you seeing build fails with latest Sampler? Curious what fails...

**Comment by NEllis280** [comment]
> Are you seeing build fails with latest Sampler? Curious what fails...

The latest build is failing because *i think* it's not seeing the schema.mof for one of the x resources

https://dev.azure.com/dsccommunity/ConfigMgrCBDsc/_build/results?buildId=7330&view=logs&jobId=0293d6db-8469-5a47-abbc-6f6aba61562f&j=0293d6db-8469-5a47-abbc-6f6aba61562f&t=4fff1e01-0f29-59ad-a7ee-7e9cb6dea69b

**Comment by johlju** [comment]
I created an issue to track it: https://github.com/gaelcolas/Sampler/issues/410

Have you tested that the build fails the same way on Windows too?

**Comment by johlju** [comment]
If a better workaround is to move the build stage from `ubuntu 20.04` to build worker `windows-latest`. There is an issue with MOF resources with `ubuntu-latest` (`ubuntu 20.04`) so cold be a good idea to move the build stage to `windows-latest` regardless.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/112)* status: all files reviewed, 1 unresolved discussion (waiting on @NEllis280)

___
*[`RequiredModules.psd1` line 16 at r1](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/112#-NLXFmYQ-7FTc6u4H-q7:-NLXFmYR5s_e393-1ed-:b-q80zys) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/ed12d37d7d030bbcad7925e8f07d71c7b833a1c9/RequiredModules.psd1#L16)):*
> ```PowerShell
>     ModuleBuilder               = 'latest'
>     ChangelogManagement         = '2.1.4'
>     Sampler                     = '0.116.0'
> ```

Tested to build locally and Sampler v0.116.1 (the latest version) works on Windows. So I suggest changing the build stage in azure-pipelines.yml to use vm image `windows-latest`.

From local build (no errors):
```
...
Looking for DSC Composite Resources in 'C:\source\ConfigMgrCBDsc\output\ConfigMgrCBDsc\3.1.0\DSCResources'
  Adding 'xSCCMInstall, xSCCMPreReqs' to the list of DscResource will be write in module manifest.
...
```



_Code quote:_
```PowerShell
Sampler                     = '0.116.0'
```

**Review by NEllis280 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/112)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`RequiredModules.psd1` line 16 at r1](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/112#-NLXFmYQ-7FTc6u4H-q7:-NLfi6P5-i63bBXL75dq:b-896fix) ([raw file](https://github.com/dsccommunity/configmgrcbdsc/blob/ed12d37d7d030bbcad7925e8f07d71c7b833a1c9/RequiredModules.psd1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Tested to build locally and Sampler v0.116.1 (the latest version) works on Windows. So I suggest changing the build stage in azure-pipelines.yml to use vm image `windows-latest`.

From local build (no errors):
```
...
Looking for DSC Composite Resources in 'C:\source\ConfigMgrCBDsc\output\ConfigMgrCBDsc\3.1.0\DSCResources'
  Adding 'xSCCMInstall, xSCCMPreReqs' to the list of DscResource will be write in module manifest.
...
```
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/configmgrcbdsc/112#-:-NLftFtl5BzdE2mU0eat:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NEllis280)

**Pull request merged**
